apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "my-helm-chart.name" . }}-pvc
  labels:
    {{- include "my-helm-chart.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
